#define STRINGIZE2(x) #x
#define STRINGIZE(x) STRINGIZE2(x)
#define MAJOR_VERSION 1
#define MINOR_VERSION 0
#define MAINTENANCE 0
#define BUILD 1453

#define FULL_VER STRINGIZE(MAJOR_VERSION) "." STRINGIZE(MINOR_VERSION) "." STRINGIZE(MAINTENANCE) "." STRINGIZE(BUILD)

#define PRODUCT_VER STRINGIZE(MAJOR_VERSION) "." STRINGIZE(MINOR_VERSION) "." STRINGIZE(MAINTENANCE)
